server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: auth-server-route
          uri: http://localhost:9001
          predicates:
            - Path=/auth/**
        - id: backend-server-route
          uri: http://localhost:9002
          predicates:
            - Path=/api/**
eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:9761/eureka"
logging:
  level:
    shop.bluebooktle.gateway: DEBUG
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG