spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: auth-server-route
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
        - id: backend-server-route
          uri: lb://BACKEND-SERVER
          predicates:
            - Path=/api/**

      default-filters:
        - AddResponseHeader=X-Request-Source, ${spring.application.name}

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

logging:
  level:
    shop.bluebooktle.gateway: INFO