server:
  port: 10223

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
#  elasticsearch:
#    uris: ${SPRING_ELASTICSEARCH_URIS}
#    username: ${SPRING_ELASTICSEARCH_USERNAME}
#    password: ${SPRING_ELASTICSEARCH_PASSWORD}
#  rabbitmq:
#    host: ${SPRING_RABBITMQ_HOST}
#    port: ${SPRING_RABBITMQ_PORT:5672}
#    username: ${SPRING_RABBITMQ_USERNAME}
#    password: ${SPRING_RABBITMQ_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}


logging:
  level:
    shop.bluebooktle.backend: INFO