server:
  port: 9012

spring:
  datasource:
    url: jdbc:h2:mem:bluebooktle_backend_dev;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
#  elasticsearch:
#    uris: http://localhost:9200
#  rabbitmq:
#    host: localhost


eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:9761/eureka"


logging:
  level:
    shop.bluebooktle: DEBUG
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace