spring:
  application:
    name: backend-server
  jpa:
    open-in-view: false
#  elasticsearch:
#    uris: ${SPRING_ELASTICSEARCH_URIS}
#    username: ${SPRING_ELASTICSEARCH_USERNAME}
#    password: ${SPRING_ELASTICSEARCH_PASSWORD}
#  rabbitmq:
#    host: ${SPRING_RABBITMQ_HOST}
#    port: ${SPRING_RABBITMQ_PORT:5672}
#    username: ${SPRING_RABBITMQ_USERNAME}
#    password: ${SPRING_RABBITMQ_PASSWORD}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

logging:
  level:
    shop.bluebooktle.backend: INFO