server:
  port: 9012

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bluebooktle
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
#  elasticsearch:
#    uris: http://localhost:9200
#  rabbitmq:
#    host: localhost


eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:9761/eureka"

jwt:
  secret: ${JWT_SECRET_KEY_LOCAL}
  access-token-validity-seconds: 1800
  refresh-token-validity-seconds: 3600

logging:
  level:
    shop.bluebooktle: DEBUG
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace