spring:
  application:
    name: backend-server

  config:
    import: optional:configserver:${CONFIG_SERVER_URI}

  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    path: /api-docs.html

# 테스트용 키
encrypt:
  key: WpqWJ+qndIaLgP1udQD7lUUuaeARZEvOzHefTNS23hA=

