server:
  port: 9012

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bluebooktle
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  #  elasticsearch:
  #    uris: http://localhost:9200
  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:9761/eureka"

# 이미지저장서버 minio
minio:
  endpoint: http://storage.java21.net:8000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: bluebooktle-bookimage

jwt:
  secret: ${JWT_SECRET_KEY_LOCAL}
  access-token-validity-seconds: 1800
  refresh-token-validity-seconds: 3600

logging:
  level:
    shop.bluebooktle: DEBUG
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

mq:
  queue:
    birthday: BB.local.birthday.queue
    birthday-dlq: BB.local.birthday.queue.dlq
    direct: BB.local.direct.queue
    direct-dlq: BB.local.direct.queue.dlq
    welcome: BB.local.welcome.queue
    welcome-dlq: BB.local.welcome.queue.dlq
  exchange:
    birthday: local.birthday.exchange
    birthday-dlx: local.birthday.dlx
    direct: local.direct.exchange
    direct-dlx: local.direct.dlx
    welcome: local.welcome.exchange
    welcome-dlx: local.welcome.dlx

encrypt:
  key: WpqWJ+qndIaLgP1udQD7lUUuaeARZEvOzHefTNS23hA=