server:
  port: 9080

eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:9761/eureka"


logging:
  level:
    action.in.blog: DEBUG
    shop.bluebooktle.book: DEBUG
    org.hibernate.SQL: DEBUG
    shop.bluebooktle.frontend.repository: DEBUG  # 패키지명을 정확하게 지정
    org.springframework.cloud.openfeign: DEBUG

    # Jackson ObjectMapper 관련 로거 (역직렬화 문제 파악에 도움)
    com.fasterxml.jackson.databind: DEBUG # 또는 TRACE (매우 상세)

    # HTTP 클라이언트 로거 (Apache HttpClient 또는 OkHttp 사용 시)
    # org.apache.http: DEBUG
    # okhttp3: DEBUG


