spring:
  application:
    name: frontend-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true