server:
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bluebooktle
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    #        use_sql_comments: true
    #        highlight_sql: true
    #        auto_quote_keyword: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:9761/eureka"

toss:
  api:
    url: https://api.tosspayments.com/v1
  secret-key: test_sk_LlDJaYngroXzQGEQlMlv8ezGdRpX
  client-key: test_ck_0RnYX2w532oJMLLx9JBPVNeyqApQ

logging:
  level:
    shop.bluebooktle.book: DEBUG
    org.hibernate.SQL: DEBUG
    shop.bluebooktle.frontend.repository: DEBUG