spring:
  application:
    name: auth-server

  config:
    import: optional:configserver:${CONFIG_SERVER_URI}

  jpa:
    open-in-view: false

oauth:
  payco:
    client-id: "3RDKLuGWlBifp1UfHtinDmZ"
