server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bluebooktle
    username: root
    password: marf1114!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 287

eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:9761/eureka"


jwt:
  secret: ${JWT_SECRET_KEY_LOCAL}
  access-token-validity-seconds: 1800
  refresh-token-validity-seconds: 3600

logging:
  level:
    shop.bluebooktle.auth: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    com.zaxxer.hikari: DEBUG