server:
  port: 9011

spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/nhn_academy_123
    username: nhn_academy_123
    password: tZ0ejmrk!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    #        use_sql_comments: true
    #        highlight_sql: true
    #        auto_quote_keyword: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 287

eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:9761/eureka"


jwt:
  secret: ${JWT_SECRET_KEY_LOCAL}
  access-token-validity-seconds: 1800
  refresh-token-validity-seconds: 3600
