server:
  port: 10212

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity-seconds: 7200
  refresh-token-validity-seconds: 86400

logging:
  level:
    shop.bluebooktle.auth: INFO