server:
  port: 9011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bluebooktle
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:9761/eureka"


jwt:
  secret: ${JWT_SECRET_KEY_LOCAL}
  access-token-validity-seconds: 5
  refresh-token-validity-seconds: 3600
