server:
  port: 9011

spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be9_team1_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: project_be9_team1
    password: /JFn8Qzhe8o(NO1r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: "http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:9761/eureka"


jwt:
  secret: ${JWT_SECRET_KEY_LOCAL}
  access-token-validity-seconds: 1800
  refresh-token-validity-seconds: 3600

oauth:
  payco:
    client-id: "3RDKLuGWlBifp1UfHtinDmZ"
    client-secret: Gtq69R7bRy6DN2LVjEdiePoH
    redirect-uri: "http://www.localhost:9080/oauth/payco"
    auth-url: "https://id.payco.com"
    api-url: "https://apis-payco.krp.toastoven.net"

mq:
  queue:
    welcome: BB.local.welcome.queue
  exchange:
    welcome: local.welcome.exchange

encrypt:
  key: WpqWJ+qndIaLgP1udQD7lUUuaeARZEvOzHefTNS23hA=