server:
  port: 9001

spring:
  datasource:
    url: jdbc:h2:mem:bluebooktle_dev;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      
eureka:
  client:
    enabled: false

logging:
  level:
    shop.bluebooktle.member: DEBUG
    org.hibernate.SQL: DEBUG
