server:
  port: 10220
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  server:
    enable-self-preservation: true
logging:
  level:
    shop.bluebooktle.eureka: INFO