spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 # 단일 서버 운영 시 설정 (클러스터 시 변경)

logging:
  level:
    shop.bluebooktle.eureka: INFO