server:
  port: 9761


eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://blue:blueBooktle12@localhost:9761/eureka/

