### 작가 생성
POST http://localhost:9012/api/authors
Content-Type: application/json

{
  "name": "문소연",
  "description": "문소연_description"

}

### 특정 작가 조회
GET http://localhost:9012/api/authors/1

### 작가 수정
PUT http://localhost:9012/api/authors/1
Content-Type: application/json

{
  "name": "곰소연",
  "description": "곰소연_description"
}

### 작가 삭제
DELETE http://localhost:9012/api/authors/1