### 작가 생성
POST http://localhost:9012/api/authors
Content-Type: application/json

{
  "name": "홍길동",
  "description": "홍길동_description"

}

### 특정 작가 조회
GET http://localhost:9012/api/authors/1

### 작가 수정_1
PATCH http://localhost:9012/api/authors/1
Content-Type: application/json

{
  "name": "홍길동 (수정)",
  "description": "홍길동_description (수정)"
}

### 작가 수정_2
PATCH http://localhost:9012/api/authors/1
Content-Type: application/json

{
  "name": "홍길동",
  "description": "홍길동_description (수정)"
}

### 작가 삭제
DELETE http://localhost:9012/api/authors/1