
#도서관련 모든정보 (작가,출판사,태그,이미지,카테고리) 한번에 등록 아직 수정필요!!

### 도서 직접 등록
POST http://localhost:9012/api/books/all
Content-Type: application/json

{
  "title": "자바 개발",
  "author": [
    "작가1",
    "작가2"
  ],
  "publisher": "출판사",
  "tag": [
    "태그1",
    "태그2"
  ],
  "imageUrl": [
    "https://image.aladin.co.kr/product/35650/80/coversum/k762036819_1.jpg"
  ],
  "category": [
    "카테고리1",
    "카테고리2"
  ],
  "isbn": "1234567890123",
  "description": "테스트 설명",
  "publishDate": "2025-05-12",
  "price": 20000,
  "salePrice": 18000,
  "stock": 99,
  "isPackable": true,
  "state": "AVAILABLE"
}

### 도서 조회 - book id로
GET http://localhost:9012/api/books/all/1
Content-Type: application/json

### 모든 도서 조회 - 제목으로
GET http://localhost:9012/api/books/all/by-title?title=제목
Content-Type: application/json

#### 메인페이지에 표시될 정보(id, title, author, price, salePrice, imgUrl) 조회
#GET http://localhost:9012/api/books/main/1
#Content-Type: application/json
#
#### 제목으로 검색하여 표시될 정보(id, title, author, price, salePrice, imgUrl) 조회
#GET http://localhost:9012/api/books/search?title=제목
#Content-Type: application/json

### minio Presigned URL 발급 요청
GET http://localhost:9012/api/books/image/upload-url?fileName=cover.jpg
Accept: application/json

