@port = 9012
@baseUrl = http://localhost:{{port}}/api/aladin/books

@tagUrl = http://localhost:{{port}}/api/tags

@categoryUrl = http://localhost:{{port}}/api/categories
@category1 = 1
@category1_1 = 2
@category1_2 = 3
@category1_1_1 = 4

@publisherUrl = http://localhost:{{port}}/api/publishers
@publisher_test_1 = 1

### 태그 등록 성공 - 1
POST {{tagUrl}}
Content-Type: application/json

{
  "name": "태그테스트1"
}

### 태그 등록 성공 - 2
POST {{tagUrl}}
Content-Type: application/json

{
  "name": "태그테스트2"
}

### 태그 등록 성공 - 3
POST {{tagUrl}}
Content-Type: application/json

{
  "name": "태그테스트3"
}

### 최상위 카테고리 등록 1
POST {{categoryUrl}}
Content-Type: application/json

{
  "rootCategoryName": "카테고리1",
  "childCategoryName": "카테고리1_1"
}

### 카테고리1의 하위 카테고리 등록 성공
POST {{categoryUrl}}/{{category1}}
Content-Type: application/json

{
  "name": "카테고리1_2"
}

### 카테고리1_1의 하위 카테고리 등록
POST {{categoryUrl}}/{{category1_1}}
Content-Type: application/json

{
  "name": "카테고리1_1_1"
}

### 작가 등록
POST http://localhost:{{port}}/api/authors
Content-Type: application/json

{
  "name": "홍길동"
}

### 출판사 등록 성공 - 1
POST {{publisherUrl}}
Content-Type: application/json

{
  "name": "출판사테스트1"
}


### 도서 테이블 직접등록
POST http://localhost:{{port}}/api/books
Content-Type: application/json

{
  "title": "테스트 제목",
  "authorIdList": [
    1
  ],
  "publisherIdList": [
    1
  ],
  "tagIdList": [
    1,
    2
  ],
  "index": "목차",
  "imgUrl": "https://image.aladin.co.kr/product/35650/80/coversum/k762036819_1.jpg",
  "categoryIdList": [
    2,
    3
  ],
  "description": "테스트 설명",
  "isbn": "1234567890125",
  "publishDate": "2025-05-15",
  "price": 20000,
  "salePrice": 18000,
  "stock": 99,
  "isPackable": true,
  "state": "AVAILABLE",
  "imgUrl": "https://image.aladin.co.kr/product/13537/89/cover200/k762532810_1.jpg"
}

### 도서 좋아요 등록(샘플)
POST http://localhost:9012/api/books/1/likes?userId=1
Content-Type: application/json

### (옵션) 도서의 좋아요 상태 조회
GET http://localhost:9012/api/books/1/likes/status?userId=1
Accept: application/json

### (옵션) 내가 좋아요한 도서 목록 조회
GET http://localhost:9012/api/books/likes?userId=1
Accept: application/json
