@port = 9012
@baseUrl = http://localhost:{{port}}/api/aladin/books

@tagUrl = http://localhost:{{port}}/api/tags

@categoryUrl = http://localhost:{{port}}/api/categories
@category1 = 1
@category1_1 = 2
@category1_2 = 3
@category1_1_1 = 4

@publisherUrl = http://localhost:{{port}}/api/publishers
@publisher_test_1 = 1

### 태그 등록 성공 - 1
POST {{tagUrl}}
Content-Type: application/json

{
  "name": "태그테스트a"
}

### 태그 등록 성공 - 2
POST {{tagUrl}}
Content-Type: application/json

{
  "name": "태그테스트b"
}

### 태그 등록 성공 - 3
POST {{tagUrl}}
Content-Type: application/json

{
  "name": "태그테스트c"
}

### 최상위 카테고리 등록 1
POST {{categoryUrl}}
Content-Type: application/json

{
  "rootCategoryName": "카테고리a",
  "childCategoryName": "카테고리a_a"
}

### 카테고리1의 하위 카테고리 등록 성공
POST {{categoryUrl}}/{{category1}}
Content-Type: application/json

{
  "name": "카테고리a_b"
}

### 카테고리1_1의 하위 카테고리 등록
POST {{categoryUrl}}/{{category1_1}}
Content-Type: application/json

{
  "name": "카테고리a_a_a"
}

### 작가 등록
POST http://localhost:{{port}}/api/authors
Content-Type: application/json

{
  "name": "홍길동a"
}

### 출판사 등록 성공 - 1
POST {{publisherUrl}}
Content-Type: application/json

{
  "name": "출판사테스트b"
}

### 도서 테이블 직접등록
POST http://localhost:{{port}}/api/books
Content-Type: application/json

{
  "title": "테스트 제목a",
  "authorIdList": [
    3
  ],
  "publisherIdList": [
    1
  ],
  "tagIdList": [
    4,
    5
  ],
  "ThumbnailUrl": "https://image.aladin.co.kr/product/35650/80/coversum/22.jpg",
  "categoryIdList": [
    5,
    6
  ],
  "description": "테스트 설명",
  "isbn": "1234567890120",
  "publishDate": "2025-05-15",
  "price": 20000,
  "salePrice": 18000,
  "stock": 99,
  "isPackable": true,
  "state": "AVAILABLE"
}

### 도서 테이블 조회
GET http://localhost:9012/api/books/1
Content-Type: application/json

### 도서 테이블 수정
PUT http://localhost:9012/api/books/1
Content-Type: application/json

{
  "title": "테스트 제목 수정",
  "description": "테스트 설명 수정"
}

### 도서 테이블 삭제
DELETE http://localhost:9012/api/books/1