@port = 9012

@baseUrl = http://localhost:{{port}}/api
@bookUrl = http://localhost:{{port}}/api/books
@categoryUrl = http://localhost:{{port}}/api/categories

@category1 = 1
@category1_1 = 2
@category1_2 = 3
@category1_1_1 = 4
@category1_1_new = 5

### 도서 등록1
POST {{bookUrl}}
Content-Type: application/json

{
  "title": "아낌없이 주는 나무",
  "description": "아낌없이 주는 나무 설명",
  "isbn": "9780060256654",
  "publishDate": "2025-05-15"
}

### 도서 등록2
POST {{bookUrl}}
Content-Type: application/json

{
  "title": "소년은 온다",
  "description": "소년은 온다 설명",
  "isbn": "9788936434120",
  "publishDate": "2025-05-15"
}


### 최상위 카테고리 등록 1
POST {{categoryUrl}}
Content-Type: application/json

{
  "rootCategoryName": "카테고리1",
  "childCategoryName": "카테고리1_1"
}

### 카테고리1의 하위 카테고리 등록 성공
POST {{categoryUrl}}/{{category1}}
Content-Type: application/json

{
  "name": "카테고리1_2"
}

### 카테고리1_1의 하위 카테고리 등록
POST {{categoryUrl}}/{{category1_1}}
Content-Type: application/json

{
  "name": "카테고리1_1_1"
}

### 도서 카테고리 등록 (카테고리1_1)
POST http://localhost:{{portNum}}/api/categories/{{category1_1}}/books/1

### 도서 카테고리 등록 실패 - 이미 등록된 카테고리 (카테고리1_1)
POST http://localhost:{{portNum}}/api/categories/{{category1_1}}/books/1

### 도서 카테고리 등록 (카테고리1_2)
POST http://localhost:{{portNum}}/api/categories/{{category1_2}}/books/1

### 도서 카테고리 등록 (카테고리1_2)
POST http://localhost:{{portNum}}/api/categories/{{category1_2}}/books/2

### 도서 카테고리 등록 (카테고리1_1_1)
POST http://localhost:{{portNum}}/api/categories/{{category1_1_1}}/books/2

### 카테고리1_1 삭제 (카테고리1_1_1에 등록된 도서도 연쇄적으로 삭제)
DELETE {{categoryUrl}}/{{category1_1}}

### 카테고리1의 하위 카테고리 등록 성공
POST {{categoryUrl}}/{{category1}}
Content-Type: application/json

{
  "name": "카테고리1_1"
}

### 도서 카테고리 등록 (카테고리1_1)
POST http://localhost:{{portNum}}/api/categories/{{category1_1_new}}/books/1

### 카테고리1_2에 등록된 도서 목록 반환
GET {{baseUrl}}/categories/{{category1_2}}/books

### 카테고리1_1에 등록된 도서 목록 반환
GET {{baseUrl}}/categories/{{category1_1_new}}/books


### 도서에 해당 카테고리 삭제
DELETE {{baseUrl}}/categories/{{category1_2}}/books/1