### 도서 직접등록 - 도서가 있어야 도서 판매정보를 등록할수있음
POST http://localhost:9012/api/books/only-book-table
Content-Type: application/json

{
  "title": "테스트 제목",
  "description": "테스트 설명",
  "isbn": "1234567890125",
  "publishDate": "2025-05-15"
}

### 도서 판매정보 등록  - 도서가 있어야 도서 판매정보를 등록할수있음
POST http://localhost:9012/api/book-sale-infos
Content-Type: application/json

{
  "bookId": 1,
  "price": 10000,
  "salePrice": 9000,
  "stock": 100,
  "isPackable": false,
  "state": "AVAILABLE"
}

### 도서 판매정보 조회
GET http://localhost:9012/api/book-sale-infos/1
Content-Type: application/json

### 도서 판매정보 수정
PUT http://localhost:9012/api/book-sale-infos/1
Content-Type: application/json

{
  "bookId": 1,
  "price": 50000,
  "salePrice": 40000,
  "stock": 120,
  "isPackable": true,
  "state": "LOW_STOCK"
}

### 도서 판매정보 삭제
DELETE http://localhost:9012/api/book-sale-infos/1
Content-Type: application/json