@baseUrl = http://localhost:9009/api/admin

### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 기본 배송 정책 등록 요청
POST {{baseUrl}}/delivery-rules
Content-Type: application/json

{
  "name": "기본 배송 정책",
  "price": 30000,
  "deliveryFee": 5000
}

### 제주도 추가 배송 정책
POST {{baseUrl}}/delivery-rules
Content-Type: application/json

{
  "name": "제주도 배송 정책",
  "price": 50000,
  "deliveryFee": 7000
}

### 배송 정책 조회
GET {{baseUrl}}/delivery-rules/1L

### 전체 배송 정책 조회
GET {{baseUrl}}/delivery-rules/all
Accept: application/json

### 제주도 배송정책 삭제
DELETE {{baseUrl}}/delivery-rules/2L

### 1번 정책 삭제 (기본정책 삭제 - 삭제불가 정책)
DELETE {{baseUrl}}/delivery-rules/1L