### 도서 테이블 직접등록
POST http://localhost:9002/api/book/register
Content-Type: application/json

{
  "title": "테스트 제목",
  "description": "테스트 설명",
  "isbn": "1234567890124",
  "publishDate": "2025-05-15"
}

### 도서 테이블 조회
GET http://localhost:9002/api/book/search/1
Content-Type: application/json

### 도서 테이블 수정
PUT http://localhost:9002/api/book/update/1
Content-Type: application/json

{
  "title": "테스트 제목 수정",
  "description": "테스트 설명 수정"
}

### 도서 테이블 삭제
DELETE http://localhost:9002/api/book/delete/1