@baseUrl = http://localhost:9002

### 포장 옵션 등록 1
POST {{baseUrl}}/api/options
Content-Type: application/json

{
  "name": "무지개 포장지",
  "price": 1500
}

### 포장 옵션 등록 2
POST {{baseUrl}}/api/options
Content-Type: application/json

{
  "name": "땡땡이 포장지",
  "price": 3000
}

### 포장 옵션 조회
GET {{baseUrl}}/api/options

### 포장 옵션 수정
PUT {{baseUrl}}/api/options/1
Content-Type: application/json

{
  "name": "고양이 포장지",
  "price": 2500
}

### 포장 옵션 삭제
DELETE {{baseUrl}}/api/options/1
