### PaymentType 전체 조회
GET localhost:9002/api/payments/types

### PaymentType 삽입
POST localhost:9002/api/payments/types
Content-Type: application/json

{
  "method": "신용카드"
}

### PaymentType 수정
PUT localhost:9002/api/payments/types/1
Content-Type: application/json

{
  "method": "ㅇㅅㅇ카드"
}

### PaymentType 삭제
DELETE localhost:9002/api/payments/types/2
Accept: application/json


### PaymentDetail 삽입
POST http://localhost:9002/api/payments/details
Content-Type: application/json

{
  "paymentTypeId": 1,
  "paymentKey": "exampleKey2"
}


### PaymentDetail 조회
GET http://localhost:9002/api/payments/details/2
Accept: application/json


### PaymentDetail 삭제
DELETE http://localhost:9002/api/payments/details/2
Accept: application/json