# .github/workflows/ci-cd.yml
name: CI & CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build all modules
        run: mvn -B clean install -DskipTests

      - name: Upload all JARs
        uses: actions/upload-artifact@v4
        with:
          name: all-jars
          path: '**/target/*.jar'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all JARs
        uses: actions/download-artifact@v4
        with:
          name: all-jars

      - name: Prepare remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ~/app/jars

      - name: Upload JARs to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: '**/target/*.jar'
          target: '~/app/jars/'

      - name: Run startup.sh on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x ~/startup.sh
            ~/startup.sh
