name: CI & CD

on:
  push:
    branches: [ develop ]
    paths:
      - 'backend-server/**'
      - 'frontend-server/**'
      - 'gateway-server/**'
      - 'eureka-server/**'
      - 'common-module/**'
      - 'auth-server/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'backend-server/**'
      - 'frontend-server/**'
      - 'gateway-server/**'
      - 'eureka-server/**'
      - 'common-module/**'
      - 'auth-server/**'

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.list.outputs.changed }}
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend-server:
              - 'backend-server/**'
            frontend-server:
              - 'frontend-server/**'
            gateway-server:
              - 'gateway-server/**'
            eureka-server:
              - 'eureka-server/**'
            common-module:
              - 'common-module/**'
            auth-server:
              - 'auth-server/**'

      - name: Generate final changed-services list
        id: list
        run: |
          modules=()
          [[ "${{ steps.filter.outputs.backend-server }}"  == "true" ]] && modules+=("backend-server")
          [[ "${{ steps.filter.outputs.frontend-server }}" == "true" ]] && modules+=("frontend-server")
          [[ "${{ steps.filter.outputs.gateway-server }}"  == "true" ]] && modules+=("gateway-server")
          [[ "${{ steps.filter.outputs.eureka-server }}"   == "true" ]] && modules+=("eureka-server")
          [[ "${{ steps.filter.outputs.auth-server }}"     == "true" ]] && modules+=("auth-server")
          if [[ "${{ steps.filter.outputs.common-module }}" == "true" ]]; then
            for svc in backend-server frontend-server gateway-server eureka-server auth-server; do
              [[ ! " ${modules[*]} " =~ " $svc " ]] && modules+=("$svc")
            done
          fi
          echo "changed=${modules[*]}" >> $GITHUB_OUTPUT

  build:
    needs: detect_changes
    if: needs.detect_changes.outputs.changed != ''
    runs-on: ubuntu-latest

    env:
      CONFIG_SERVER_URI: ${{ secrets.CONFIG_SERVER_URI }}
      SPRING_PROFILES_ACTIVE: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Clean & Build changed-services
        run: |
          MODULE_CSV=$(echo "${{ needs.detect_changes.outputs.changed }}" | sed 's/ /,/g')
          echo "▶ mvn clean package -pl $MODULE_CSV -am"
          mvn -B clean package -pl "$MODULE_CSV" -am -DskipTests

      - name: Upload built JARs
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: '**/target/*.jar'
          if-no-files-found: error

  deploy:
    needs: [ detect_changes, build ]
    if: needs.detect_changes.outputs.changed != ''
    runs-on: ubuntu-latest

    # ← 여기도 동일하게 ENV 주입
    env:
      CONFIG_SERVER_URI: ${{ secrets.CONFIG_SERVER_URI }}
      SPRING_PROFILES_ACTIVE: dev

    steps:
      - name: Download JARs
        uses: actions/download-artifact@v4
        with:
          name: jars
          path: downloaded_jars

      - name: Debug deploy modules
        run: |
          echo ">>> Deploy sees modules: '${{ needs.detect_changes.outputs.changed }}'"
          echo ">>> Using CONFIG_SERVER_URI=${CONFIG_SERVER_URI}"
          echo ">>> Using SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}"

      - name: Upload JARs to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "downloaded_jars"
          target: "~/app/jars/"
          strip_components: 1

      - name: Rolling deploy for services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          capture_stdout: true
          script: |
            echo ">>> SSH sees modules: ${{ needs.detect_changes.outputs.changed }}"
            chmod +x ~/startup.sh
            
            # 환경변수로 프로파일과 Config URI를 내보냄
            export SPRING_PROFILES_ACTIVE="${{ env.SPRING_PROFILES_ACTIVE }}"
            export CONFIG_SERVER_URI="${{ env.CONFIG_SERVER_URI }}"
            
            
            export SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
            export CONFIG_SERVER_URI=${CONFIG_SERVER_URI}

            for MOD in ${{ needs.detect_changes.outputs.changed }}; do
              echo "▶ Rolling deploy: $MOD"
              ~/startup.sh "$MOD"
            done