name: CI & CD

on:
  push:
    branches: [ develop ]
    paths:
      - 'backend-server/**'
      - 'frontend-server/**'
      - 'gateway-server/**'
      - 'eureka-server/**'
      - 'common-module/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'backend-server/**'
      - 'frontend-server/**'
      - 'gateway-server/**'
      - 'eureka-server/**'
      - 'common-module/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build all modules
        run: mvn -B clean install -DskipTests

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: '**/target/*.jar'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JARs
        uses: actions/download-artifact@v4
        with:
          name: jars

      - name: Prepare remote dir & deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ~/app/jars
            # JAR은 이미 ~/app/jars 로 복사됨
            chmod +x ~/startup.sh
            ~/startup.sh